logger:
  file:
    path: /opt/open5gs/install/var/log/open5gs/nrf.log

nrf:
  serving:
    - plmn_id:
        mcc: 001
        mnc: 01
  sbi:
    server:
      - address: 127.0.0.10
        port: 7777
