logger:
  file:
    path: /opt/open5gs/install/var/log/open5gs/nssf.log

nssf:
  sbi:
    server:
      - address: 127.0.0.14
        port: 7777

    client:
      nrf:
        - uri: http://127.0.0.10:7777

      # Slice list goes HERE (under sbi.client)
      nsi:
        - uri: http://127.0.0.10:7777
          s_nssai:
            sst: 1
            sd: "000000"
        - uri: http://127.0.0.10:7777
          s_nssai:
            sst: 2
            sd: "000000"
        - uri: http://127.0.0.10:7777
          s_nssai:
            sst: 3
            sd: "000000"
