logger:
  file:
    path: /opt/open5gs/install/var/log/open5gs/udm.log

udm:
  sbi:
    server:
      - address: 127.0.0.12
        port: 7777
    client:
      nrf:
        - uri: http://127.0.0.10:7777
